-- Initial schema — mirrors what backend/mysql/init.sql created in production before migrations
-- existed (task, task_history, task_execution). Generated by
-- ./gradlew :persistence:generateMigrationScript, not hand-written; MigrationSchemaTest keeps
-- this file and the Exposed *Table objects in step going forward.

CREATE TABLE IF NOT EXISTS task (id INT AUTO_INCREMENT PRIMARY KEY, host VARCHAR(50) NOT NULL, endpoint VARCHAR(255) NOT NULL, `data` JSON NULL, cron VARCHAR(20) NULL, status VARCHAR(30) NOT NULL, executed_at DATETIME(6) NULL, next_execution_at DATETIME(6) NOT NULL, created_by VARCHAR(50) NOT NULL, created_at DATETIME(6) NOT NULL);
CREATE INDEX idx_status_next_execution ON task (status, next_execution_at);
CREATE TABLE IF NOT EXISTS task_history (id INT AUTO_INCREMENT PRIMARY KEY, task_id INT NOT NULL, host VARCHAR(50) NOT NULL, endpoint VARCHAR(255) NOT NULL, `data` JSON NULL, cron VARCHAR(20) NULL, status VARCHAR(30) NOT NULL, executed_at DATETIME(6) NULL, next_execution_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_task_history_task_id__id FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS task_execution (id INT AUTO_INCREMENT PRIMARY KEY, task_id INT NOT NULL, executed_at DATETIME(6) NOT NULL, duration_ms BIGINT NOT NULL, status VARCHAR(20) NOT NULL, `result` JSON NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_task_execution_task_id__id FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
